name: Build release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install node modules
        run: npm install
      - name: Build
        run: npm run build
      - name: Commit new build
        run: |
          git config --local user.email "github-actions-bot@noreply.github.com"
          git config --local user.name "github-actions-bot"
          git add -f dist/*.js
          git commit -m "new dist"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
